server:
  port: 8083


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: quocnamle
    driverClassName: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:sqlserver://eafinalproject.database.windows.net:1433;database=shopping_cart;user=victorbahta@eafinalproject;password=Finalproject1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update

api-client:
  customer:
    name: customer-service
    url: http://localhost:8083
  product:
    name: product-service
    url: http://localhost:8083
#  username: user
#  password: pass